// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TouchInputUpdate","status":true,"description":"Pivert Touch Input Update.","parameters":{}},
{"name":"InteractiveMap","status":true,"description":"Pivert Interactive map.","parameters":{"-- Interactive map --":"","Interactive map text":"Map","Images directory":"img/map","Map image":"map"}}
];
